name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 */2 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: AdamT20054
          template: classic
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          base: header, activity, community, repositories, metadata
          repositories_forks: no
          config_display: large
          config_timezone: Europe/London
          
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_indepth: yes
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14
          
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_achievements_limit: 0 
          
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          
          plugin_habits: yes
          
          plugin_lines: yes
          
          plugin_notable: yes
          

          
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 365
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: current
